import type { PropertyData } from "@/modules/property/models/property.model";

export const PROPERTIES: PropertyData[] = [
  {
    id: "1",
    title: "2 BHK Semi-furnished Flat",
    type: "flat",
    purpose: "rent",
    areaLabel: "950 sq ft",
    areaSqFt: 950,
    furnished: true,
    facing: "East",
    location: "Vijay Nagar, Indore",
    address: "202, Sunshine Residency, Vijay Nagar",
    price: 18000,
    priceLabel: "₹18,000 / month",
    rooms: "2 BHK",
    bathrooms: 2,
    description: "Well ventilated flat near main road and schools.",
    amenities: ["Lift", "Security", "Power Backup"],
    nearbyPlaces: ["School", "Mall", "Hospital"],
    images: ["https://images.pexels.com/photos/259580/pexels-photo-259580.jpeg"],
    contact: "9876543210",
    floor: "2nd floor",
    parking: true,
    ownerName: "Rahul Sharma",
    show: true,
    creatorId: "user_1",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Residential Plot for Sale",
    type: "land",
    purpose: "sale",
    areaLabel: "1200 sq ft",
    areaSqFt: 1200,
    location: "AB Road, Indore",
    address: "AB Road, Near XYZ Colony",
    price: 2500000,
    priceLabel: "₹25 Lakh",
    description: "Freehold plot in a developing gated colony.",
    amenities: ["Gated Society"],
    nearbyPlaces: ["Highway", "Market"],
    images: ["https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg"],
    contact: "9876500000",
    parking: false,
    furnished: false,
    facing: "North",
    rooms: "",
    ownerName: "Sanjay Verma",
    show: true,
    creatorId: "user_2",
  },

  // ---------------- NEW MOCK DATA ADDED ----------------

  {
    id: "3",
    title: "3 BHK Independent House",
    type: "house",
    purpose: "sale",
    areaLabel: "1800 sq ft",
    areaSqFt: 1800,
    furnished: false,
    facing: "West",
    location: "Rajendra Nagar, Indore",
    price: 6200000,
    priceLabel: "₹62 Lakh",
    rooms: "3 BHK",
    bathrooms: 3,
    description: "Corner house with spacious rooms and garden space.",
    amenities: ["Parking", "Garden", "Borewell"],
    nearbyPlaces: ["Temple", "Garden", "Gym"],
    images: ["https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg"],
    contact: "9988776655",
    parking: true,
    ownerName: "Amit Patel",
    show: true,
    creatorId: "user_3",
  },
  {
    id: "4",
    title: "Commercial Shop for Rent",
    type: "shop",
    purpose: "rent",
    areaLabel: "300 sq ft",
    areaSqFt: 300,
    furnished: true,
    location: "Sarafa Market, Indore",
    price: 35000,
    priceLabel: "₹35,000 / month",
    description: "Premium location shop suitable for jewellery or garment businesses.",
    amenities: ["Security", "Front Shutter", "Main Road"],
    nearbyPlaces: ["Market", "Restaurants"],
    images: ["https://images.pexels.com/photos/264507/pexels-photo-264507.jpeg"],
    contact: "7894561230",
    parking: false,
    ownerName: "Manish Jain",
    show: true,
    creatorId: "user_4",
  },
  {
    id: "5",
    title: "Luxury Villa with Private Lawn",
    type: "villa",
    purpose: "sale",
    areaLabel: "3500 sq ft",
    areaSqFt: 3500,
    furnished: true,
    facing: "South",
    location: "Scheme 78, Indore",
    price: 14500000,
    priceLabel: "₹1.45 Cr",
    rooms: "5 BHK",
    bathrooms: 5,
    description: "Modern architecture villa with premium interiors and pool.",
    amenities: ["Swimming Pool", "Security", "Garden", "Club House"],
    nearbyPlaces: ["Park", "School", "Hospital"],
    images: ["https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg"],
    contact: "8899776655",
    parking: true,
    ownerName: "Vivek Bansal",
    show: true,
    creatorId: "user_5",
  },
  {
    id: "6",
    title: "Warehouse Space for Lease",
    type: "warehouse",
    purpose: "rent",
    areaLabel: "10,000 sq ft",
    areaSqFt: 10000,
    location: "Dewas Naka, Indore",
    price: 200000,
    priceLabel: "₹2,00,000 / month",
    description: "Well-connected warehouse suitable for logistics & storage.",
    amenities: ["Parking", "24x7 Security", "Wide Road Access"],
    nearbyPlaces: ["Highway"],
    images: ["https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg"],
    contact: "9009009000",
    parking: true,
    ownerName: "Logistics India Corp",
    show: true,
    creatorId: "user_6",
  },
  {
    id: "7",
    title: "1 RK Studio Flat",
    type: "flat",
    purpose: "rent",
    areaLabel: "450 sq ft",
    areaSqFt: 450,
    furnished: true,
    location: "Palasia, Indore",
    price: 9500,
    priceLabel: "₹9,500 / month",
    rooms: "1 RK",
    bathrooms: 1,
    description: "Compact studio apartment ideal for students & singles.",
    amenities: ["Lift", "Security"],
    nearbyPlaces: ["College", "Coffee Shops"],
    images: ["https://images.pexels.com/photos/271632/pexels-photo-271632.jpeg"],
    contact: "7012345678",
    parking: false,
    ownerName: "Ritesh Mehta",
    show: true,
    creatorId: "user_7",
  },
  {
    id: "8",
    title: "Fully Furnished Office Space",
    type: "office",
    purpose: "rent",
    areaLabel: "1500 sq ft",
    areaSqFt: 1500,
    furnished: true,
    location: "South Tukoganj, Indore",
    price: 80000,
    priceLabel: "₹80,000 / month",
    description: "Ready office space with cabins, conference hall & workstations.",
    amenities: ["AC", "Reception", "Parking"],
    nearbyPlaces: ["Railway Station", "Mall"],
    images: ["https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg"],
    contact: "9823456721",
    parking: true,
    ownerName: "Global Enterprises",
    show: true,
    creatorId: "user_8",
  },
  {
    id: "9",
    title: "4 BHK Premium Duplex",
    type: "house",
    purpose: "sale",
    areaLabel: "2400 sq ft",
    areaSqFt: 2400,
    furnished: false,
    facing: "East",
    location: "Bicholi Mardana, Indore",
    price: 9700000,
    priceLabel: "₹97 Lakh",
    rooms: "4 BHK",
    bathrooms: 4,
    description: "Newly constructed duplex with spacious hall and modular kitchen.",
    amenities: ["Parking", "Solar Panel", "Terrace"],
    nearbyPlaces: ["Supermarket", "Club House"],
    images: ["https://images.pexels.com/photos/7031409/pexels-photo-7031409.jpeg"],
    contact: "8123456789",
    parking: true,
    ownerName: "Mahesh Soni",
    show: true,
    creatorId: "user_9",
  },
    {
    id: "10",
    title: "2 BHK Family Apartment",
    type: "flat",
    purpose: "rent",
    areaLabel: "820 sq ft",
    areaSqFt: 820,
    furnished: false,
    facing: "North",
    location: "Scheme 54, Indore",
    price: 14000,
    priceLabel: "₹14,000 / month",
    rooms: "2 BHK",
    bathrooms: 2,
    description: "Ideal for small families, near schools and parks.",
    amenities: ["Lift", "CCTV", "Security"],
    nearbyPlaces: ["Park", "School"],
    images: ["https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg"],
    contact: "9001234567",
    parking: true,
    ownerName: "Suman Rao",
    show: true,
    creatorId: "user_10",
  },
  {
    id: "11",
    title: "Prime Commercial Showroom",
    type: "shop",
    purpose: "sale",
    areaLabel: "650 sq ft",
    areaSqFt: 650,
    furnished: true,
    location: "Treasure Island Road, Indore",
    price: 7800000,
    priceLabel: "₹78 Lakh",
    description: "Premium location with high footfall, ideal for branded outlets.",
    amenities: ["Security", "Parking"],
    nearbyPlaces: ["Mall", "Main Road"],
    images: ["https://images.pexels.com/photos/3965545/pexels-photo-3965545.jpeg"],
    contact: "9102223344",
    parking: true,
    ownerName: "Retail Enterprises",
    show: true,
    creatorId: "user_11",
  },
  {
    id: "12",
    title: "Farmhouse Land Available",
    type: "land",
    purpose: "sale",
    areaLabel: "1.5 Acre",
    areaSqFt: 65340,
    furnished: false,
    facing: "Open",
    location: "Rau Bypass, Indore",
    price: 5200000,
    priceLabel: "₹52 Lakh",
    description: "Ideal for resort or farmhouse project.",
    amenities: [],
    nearbyPlaces: ["Highway", "Farm Residences"],
    images: ["https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg"],
    contact: "9812398765",
    parking: true,
    ownerName: "Rau Builders",
    show: true,
    creatorId: "user_12",
  },
  {
    id: "13",
    title: "Corporate Office Space",
    type: "office",
    purpose: "rent",
    areaLabel: "2200 sq ft",
    areaSqFt: 2200,
    furnished: true,
    location: "Vijay Nagar Corporate Zone",
    price: 155000,
    priceLabel: "₹1,55,000 / month",
    description: "Fully furnished office with 30-seater space and conference hall.",
    amenities: ["AC", "Parking", "High-speed Internet"],
    nearbyPlaces: ["IT Park", "Coffee Shop"],
    images: ["https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg"],
    contact: "9623345566",
    parking: true,
    ownerName: "SmartSpace Pvt Ltd",
    show: true,
    creatorId: "user_13",
  },
  {
    id: "14",
    title: "3 BHK Row House with Backyard",
    type: "house",
    purpose: "sale",
    areaLabel: "2100 sq ft",
    areaSqFt: 2100,
    furnished: false,
    location: "Mahalaxmi Nagar, Indore",
    price: 8800000,
    priceLabel: "₹88 Lakh",
    rooms: "3 BHK",
    bathrooms: 3,
    facing: "South",
    description: "Spacious row house ideal for big families.",
    amenities: ["Backyard", "Parking"],
    nearbyPlaces: ["Hospital", "School"],
    images: ["https://images.pexels.com/photos/259558/pexels-photo-259558.jpeg"],
    contact: "8976542199",
    parking: true,
    ownerName: "Kiran Homes",
    show: true,
    creatorId: "user_14",
  },

];
